import { ASSETS } from './galleryAssets';

/**
 * Aarohan gallery frames — data only, so GalleryViewfinder stays purely
 * structural. Same content/component split as ../AboutUs/aboutContent.js and
 * ../Home/homeContent.js.
 *
 * ── Why this is split from galleryAssets.js ──
 *
 * This file is hand-maintained and holds the two things a person decides: which
 * photos appear, and in what order. galleryAssets.js is generated by
 * scripts/resize-aarohan.ps1 and holds only what a machine can derive: the file
 * each frame resolves to and its pixel dimensions.
 *
 * The split means regenerating the derivatives — after adding a photo, or
 * retuning quality — can never clobber a caption or reorder the gallery. It also
 * keeps a generated file out of the way of code review.
 *
 * Neither file goes through Assets/Images/index.js. That barrel is imported by
 * every route, so putting fourteen gallery derivatives in it would make them a
 * dependency of pages that never show the gallery.
 *
 * ── Why each frame carries a separate `thumb` ──
 *
 * The viewfinder shows one large frame plus a contact strip of seven
 * thumbnails. Pointing the strip at the full-size files defeats the whole
 * design: a 90px-wide thumbnail sourced from a 14.9 MB original still decodes
 * the entire 14.9 MB bitmap. The strip needs its own small assets, or it would
 * be cheaper to show nothing at all.
 *
 * Until the resize script runs, `thumb` and `full` are the same original and the
 * page still ships ~44 MB. It is already better than the pinned deck it replaced
 * — one live frame instead of seven promoted compositor layers, and no pin — but
 * running the script is what actually completes the fix. See galleryAssets.js.
 */

export const FRAMES = [
  { ...ASSETS.ARHN1, caption: 'Grand Inauguration' },
  { ...ASSETS.ARHN2, caption: 'Robotics Arena' },
  { ...ASSETS.ARHN3, caption: 'Cultural Nights' },
  { ...ASSETS.ARHN4, caption: 'Hackathon' },
  { ...ASSETS.ARHN5, caption: 'Inspiratie Talks' },
  { ...ASSETS.ARHN6, caption: 'Decathlon Battle' },
  { ...ASSETS.ARHN8, caption: 'Closing Ceremony' },
];

/**
 * What useDecodedImages warms on this page.
 *
 * The thumbnails, because the contact strip is visible the moment the gallery
 * scrolls into view and seven missing thumbnails read as a broken control. Plus
 * frame 0, which is the one large image on screen when the reader arrives.
 *
 * Everything else is warmed on demand: the viewfinder preloads the active
 * frame's immediate neighbours, so stepping is served from cache without ever
 * holding more than a couple of large bitmaps at once. The previous build
 * decoded all seven full-size images up front in a single Promise.all.
 *
 * De-duplicated via a Set because before the resize script runs `thumb` and
 * `full` are the same file, and warming each original twice would be pure waste.
 * Once the derivatives exist the two sets are disjoint and all eight entries
 * survive — seven thumbnails is ~100 KB in total.
 */
export const WARM_ON_ARRIVAL = [
  ...new Set([...FRAMES.map((f) => f.thumb), FRAMES[0].full]),
];
